### ISSUE TITLE
School Sync Issue

### ISSUE THREAD

**Issue by guygunarathne** [TheAlphaSchoolSystemPTYLTD/student-details#13] opened 2019-05-30 03:58 UTC
School STUDENT API Sync issue

Error message:

We got the below error message

501 - Header values specify a method that is not implemented.
 
The page you are looking for cannot be displayed because a header value in the request does not match certain configuration settings on the Web server. For example, a request header might specify a POST to a static file that cannot be posted to, or specify a Transfer-Encoding value that cannot make use of compression.

**Comment by jtc** [comment] 2019-06-06 00:39
Can you please post a code sample including generation and submission of the API request, that would allow someone to reproduce this issue.

**Comment by guygunarathne** [comment] 2019-06-07 12:57
Hi @jtc 
1. I am using getStudentsDetails method with following request:-

https://api.tassweb.com.au/tassweb/api/?method=GetStudentsDetails&appcode=ROLL001&company=10&v=2&token=u7j1s64F8si1JJE2DZVc7vvtOrUkTkKTCgoRS9xtcMfr3FYqfWXvvIn5Xk%2BdYPMkiqBRn%2BlUQKt0MeyzO%2F6oEczOJHmErtpXJf16fp%2Bv1wcaHfaYl4VzzztQQ7RtdJrI

this is not working showing: 

**401 - Unauthorized: Access is denied due to invalid credentials.**

2. **getCommunicationRulesDetails** to get Parent's relationship according to Student  with following request:-
https://api.tassweb.com.au/tassweb/api/?method=GetCommunicationRulesDetails&appcode=ROLL001&company=10&v=2&token=u7j1s64F8si1JJE2DZVc7vvtOrUkTkKTCgoRS9xtcMcJJiv0Dk92np5ldF28ZeaMJKzZF36ej%2FDLBiTBvveJxQ%3D%3D

this is not working showing: 
**401 - Unauthorized: Access is denied due to invalid credentials.**

**Comment by guygunarathne** [comment] 2019-06-07 12:57
Hi @jtc 
1. I am using getStudentsDetails method with following request:-

https://api.tassweb.com.au/tassweb/api/?method=GetStudentsDetails&appcode=ROLL001&company=10&v=2&token=u7j1s64F8si1JJE2DZVc7vvtOrUkTkKTCgoRS9xtcMfr3FYqfWXvvIn5Xk%2BdYPMkiqBRn%2BlUQKt0MeyzO%2F6oEczOJHmErtpXJf16fp%2Bv1wcaHfaYl4VzzztQQ7RtdJrI

this is not working showing: 

**401 - Unauthorized: Access is denied due to invalid credentials.**

2. **getCommunicationRulesDetails** to get Parent's relationship according to Student  with following request:-
https://api.tassweb.com.au/tassweb/api/?method=GetCommunicationRulesDetails&appcode=ROLL001&company=10&v=2&token=u7j1s64F8si1JJE2DZVc7vvtOrUkTkKTCgoRS9xtcMcJJiv0Dk92np5ldF28ZeaMJKzZF36ej%2FDLBiTBvveJxQ%3D%3D

this is not working showing: 
**401 - Unauthorized: Access is denied due to invalid credentials.**

**Comment by jtc** [comment] 2019-06-07 14:05
Are you working with a specific school on a project here?

Or have you requested access to the TASS API sandbox for testing?

**Comment by guygunarathne** [comment] 2019-06-10 05:16
Yes, i am working on Specific school project but for now i am using sandbox credentials for testing TASS API data as per above commented URL request.

**Comment by jtc** [comment] 2019-06-10 06:45
Sure, I'd be happy to take a look at the code generating your API requests to ensure it does work against my TASS instance - which could narrow down if it is a code issue, or an issue with the token key TASS have issued you.

Otherwise, being the TASS API sandbox, might need to leave it up to TASS staff to see if they can send you the log messages for your API requests.

**Comment by guygunarathne** [comment] 2019-06-11 04:56
Great!
Yes, please have a look a at the code generating from API, i am using following credentials for sandbox:

Company Code: 10
Application Code: ROLL001
Token Key: ek733FwFKNdrh3J8fd+RjQ==
TASS URL: https://api.tassweb.com.au/tassweb/api

[Rollbook-TASS.docx](https://github.com/TheAlphaSchoolSystemPTYLTD/student-details/files/3274811/Rollbook-TASS.docx)

**Comment by jtc** [comment] 2019-06-11 05:58
Thanks for the info 😄 

Alright, using the https://github.com/TheAlphaSchoolSystemPTYLTD/api-introduction/blob/master/encryptDecrypt.php example...

I have generated an API request to my own TASS instance using my own company/app/token key/URL, and this was successful.

I have then tried, using the same example code, with the API details you have provided, and received the same 401 error.

So possibly, the token key TASS provided you has since been revoked—you'll need to get in touch with them.

**Comment by guygunarathne** [comment] 2019-06-11 06:05
Thanks for confirmation!
I will check with TASS.

**Comment by guygunarathne** [comment] 2019-06-11 06:13
Hi Joshua,

I've sent this to Tammy from TASS to confirm if our api token has been revoked.

Cheers

Guy

________________________________

**Comment by guygunarathne** [comment] 2019-06-13 03:07
Hi @jtc 

I haven't heard back from Tammy and this is getting urgent - can you please have a look and let me know please

**Comment by jtc** [comment] 2019-06-13 03:38
Hi @guygunarathne 

Sorry but I'm not a TASS employee, so there's not much more I can do since it looks like TASS may have revoked the token key.

Another option is to see if you can get API access through the school you're working with⁠—the school IT staff would be able to set that up for you.

**Comment by guygunarathne** [comment] 2019-06-13 04:08
Hi @jtc 

If we paste the school URL - would it be private and secure? Just so you can trouble shoot from your end as well

**Comment by jtc** [comment] 2019-06-13 04:23
@guygunarathne Anyone with the full URL including the GET parameters would be able to access the school's private data, so best not to paste it here.

With the school's permission, you're welcome to shoot it through to joshua@cowper.id.au - in case I can't get the URL to work, I may need the token key.

**Comment by guygunarathne** [comment] 2019-06-20 04:31
Ok looks like our sandbox environment is back but for the school we are setting up, we are still receiving the error: 501 - header values specify a method that is not implemented" when attempting to use endpoint. Please assist

**Comment by jtc** [comment] 2019-06-20 05:39
The only general advice I can provide here is that the TASS API only supports the GET and POST HTTP methods, so ensure you are using one of those. TASS.web > System Admin > Utilities > API Gateway Maintenance > TASS APIs > Log _may_ give you some details, if the request is getting that far, otherwise IIS Logs may be all you have.

It sounds like you have token keys for both the TASS Sandbox, and your specific school, now? Do you receive this error only for the school, and not for the sandbox? Do you get the error when accessing a generated URL through a browser, or only when making the request within your project?

Need to narrow down on what TASS servers and under what circumstances the error is occurring.

**Comment by ricardorusson** [comment] 2019-08-22 04:55
Closing issue. Please feel free to re-open if required.
Thanks.

**Closed by ricardorusson** 2019-08-22 04:55 UTC
